# Generated by Django 4.2.2 on 2023-06-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=122)),
                ('rname', models.CharField(max_length=122)),
                ('money', models.IntegerField()),
                ('tdate', models.DateTimeField()),
            ],
        ),
    ]
