# Generated by Django 3.2.6 on 2021-08-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
